package-lock.json, package.json
Added package to deploy to `gh-pages` branch
Steps to test : 
`npm run deploy-storybook`
=> add github pages

package.json
=> add scope organization package

README.md, package.json, src/DropzoneHash.js, src/InputHash.js, src/index.js, src/stories/2-InputHash.stories.js, src/stories/5-DropzoneHash.stories.js, src/themes/eoscr-theme.js
- Make Dropzone component adaptative
Add new props to Dropzone component:
- *useModal:* this prop allows to use Dropzone as a modal or as a simple dropbox.
- *handleOnDropFile:* this prop allows to return the data of file previously uploaded.
- *dropZoneButtonText*
- *dropZoneText*
- *dropZoneDialogText*
- *dropZoneDialogButton*
- *sendButtonText*
- *cancelButtonText*
Add new props to inputHash component:
- *messageSuccess:* message validation when the hash is correct
- allow inputHash component to receive input text properties as `...props`
- Export Backdrop component
- Update stories
- yarn
- go to `http://localhost:9009/`
=> Add new props

src/RicardianContract.js, src/stories/4-RicardianContract.stories.js
Add Mainnet URL as default property into Ricardian contract component 
- run *yarn storybook*
- go to *http://localhost:9009*
=> Add mainnet URL

README.md, package.json, src/DropzoneHash.js
Set File as a property into DropzoneHash component
- go to `http://localhost:9009`
=> Set file as property

src/Backdrop.js, src/DropzoneHash.js, src/stories/3-Backdrop.stories.js, src/stories/6-InfiniteRegistryTableLoader.stories.js
=> fix format

README.md, package.json, src/Backdrop.js, src/stories/3-Backdrop.stories.js
_Refactor Backdrop component:_
- Change header property type in order to receive node instead string
- Add logic to start the front layer down when the breakpoint is mobile
- go to `http://localhost:9009/`
=> refactor backdrop component

README.md, package.json, src/components/AccountInfo/AccountInfo.js, src/components/BPJsonGenerator/BPJsonGenerator.js, src/components/Backdrop/Backdrop.js, src/components/InfiniteRegistryTableLoader/InfiniteRegistryTableLoader.js, yarn.lock
Refactor Backdrop in mobile version
=> refactor backdrop mobile version

README.md, package.json, src/components/Backdrop/Backdrop.js
Add useSecondaryPage as boolean property in order to allow to use a single page without front layer
- go to `http://localhost:9009`
=> add boolean prop to allow use single page

README.md, package.json, src/components/Backdrop/Backdrop.js
Add isStaticPage property in order to know if page needs the collapsible functionality
- go to `http://localhost:9009/`
=> Add property to support static page

src/components/DropzoneHash/DropzoneHash.js, src/components/DropzoneHash/FileComponent.js, src/components/IssuanceVerifier/IssuanceVerifier.js, src/components/common/DropzoneBase.js, src/components/common/index.js, src/stories/5-DropzoneHash.stories.js, src/utils/filereader.js
The structure of dropzone base functionality **needed to be restructured** in order to reuse code, provider better encapsulation and allow easier incoming implementations of new functionalities like issuance verification dialog. Please check the code and don't hesitate to give your opinion.
If you want to test the new changes, just pull changes from this branch, run `yarn run storybook` and go to **localhost:9009**
=> refactor dropzone structure and usage

src/components/Backdrop/Backdrop.js, src/components/RicardianContract/RicardianContract.js
- Add error handler to Ricardian Contract Component
- Add logic to overwrite classes for LinearProgress
- Delete useRef for frontLayer in Backdrop component
- Add logic to handler frontLayer height using `layerHeightUp` and `layerHeightDown` properties
- Add `isStaticPage` property in order to use front page content as static page (not collapsible)
- yarn
- go to `http://localhost:9009`
=> Refactor component

src/components/VisualCertificate/VisualCertificate.js
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/eoscostarica/eoscr-components/issues).
=> Apply fixes from CodeFactor

README.md, package.json, src/components/Backdrop/Backdrop.js
- Refactor Backdrop in order to add landscape orientation support 
- go to `http://localhost:9009`
=> Landscape Orientation Support

package.json, src/components/BPJsonGenerator/BPJsonGenerator.js, src/components/BPJsonGenerator/NodesForm.js
Fix latitude & longitude type from string to number
closes #58
=> fix: location output

src/components/BPJsonGenerator/Modal.js, src/components/BPJsonGenerator/NodesForm.js
closes #62 
- Delete empty json keys
- Show only relevant fields according to each type of node
=> fix: bp json node types

README.md, package.json, src/components/RicardianContract/RicardianContract.js, src/stories/4-RicardianContract.stories.js
- Add new ricardian prop
1. first step
2. next step
=> Add title prop to use custom title

package.json, yarn.lock
I am unable to import `eoscr-components` package in a project due to a depracated dependency, this PR updates the node packages and fixes the issue with the dependency
=> Update node package versions

public/robots.txt, yarn.lock
=> Add public folder

package.json, src/lib/RicardianContract/index.js, src/lib/config/index.js
- Add key for ricardian contract maps clauses and actions
1. Run `yarn storybook`
2. Go to `localhost:6006`
3. test ricardian contract story
=> (Package): Add key for ricardian contract maps clauses and actions

package.json
=> fix:(frontend): update npm version

package.json
=> ci(github): publish version 4.0.5

.github/workflows/nodejs.yml, yarn.lock
Set the node version as a temporary fix
=> fix(workflows): set node version to fix build error
